language: dart
branches:
  only:
    - master
    # Semantic version tags and legacy branches of the form "1.2.x".
    - "/^\\d+\\.\\d+\\.(\\d+([+-].*)?|x)$/"
cache:
  directories:
    - $HOME/.pub-cache

before_script:
- if-node() { if [ ! -z "$NODE_VERSION" ]; then "$@"; fi }
- if-dart() { if [ -z "$NODE_VERSION" ]; then "$@"; fi }
- if-node . "$HOME/.nvm/nvm.sh"
- if-node nvm install "$NODE_VERSION"
- if-node nvm use "$NODE_VERSION"
- if-node pub run grinder pkg-npm-dev
- if-dart pub run grinder pkg-standalone-dev

jobs:
  include:
  ## Testing

  # Testing on the Dart VM
  - dart: stable
    dart_task: {test: -x node}
  - dart: dev
    dart_task: {test: -x node}

  # Testing on Node.js
  - env: NODE_VERSION=stable
    dart_task: {test: -t node}
  # Keep these up-to-date with the latest LTS Node releases. They next need to
  # be rotated April 2021. See https://github.com/nodejs/Release.
  - env: NODE_VERSION=lts/dubnium
    dart_task: {test: -t node}
  - env: NODE_VERSION=lts/erbium
    dart_task: {test: -t node}

  # Static checks
  - dart_task: {dartanalyzer: --fatal-warnings --fatal-hints ./}
  - dart_task: dartfmt

  ## Deployment

  # Sanity check before releasing anywhere.
  - stage: sanity check
    if: &deploy-if
      (type IN (push, api)) AND (repo = sass/migrator) AND tag =~ ^\d+\.\d+\.\d+([+-].*)?$
    script: pub run grinder sanity-check-before-release

  # Deploy Linux releases to GitHub. macOS and Windows releases are deployed in
  # a later stage so that we can build native snapshots on bots with the same
  # operating system.
  - stage: deploy 1
    name: "GitHub: Linux"
    if: *deploy-if
    env: &github-env
      - GITHUB_USER=sassbot
      # GITHUB_TOKEN="..."
      - secure: "XmwFy85erVGX1EHIRlXe/vMKbJHmgrTKRu6SG713XFd2QdFRPce1VpKB/oc/x/5NbuE6LGSmPTAblfuXRiHs5PtD9p+73HzejdcOa4jkxMmU+FgPT8JuM0lpDIT/HXKW3liV+TLOytSpzJbH1EgCbaXJ4xh2CF2jzIIoZ47ylhl5jd4eZ2oip4nozOBMSwXXt4LJlGbLjINY+k/afB3Y9yP2WEPqdtjBsJNhWlXOx5IOcay5tK9iKtx6Pwt7YqQaNMopauZKEVJY4fxutE1i217pbcS+JEk+csjY0zDt40ZcdYdu3F8wV1DFKoKt/sw84ModsEBAOxG6gPTTtXYdGTGLQVK024m7x8tAc5mdJ4gx0eSaCKAhKRoo4WpESp+0gVzKxxSGscSaVkISxeV+UhDUfXa+C2rPwjEyAhByfuVq+O1zMDMMntFV5fHqg607LRPcK9swGfM7yqpBNFjXGI0ev4mhuG7Tt1ZvwBbIwcNWa1gV29Eplk6JG7OD9bkDJQC0FseUnmQ+IS6OPv8TWD+EOYLjjr0OZgKZXwUba/5w4IdNMjmxLcwhbNHqnWCvvs/0NWeLa06X5gqARKHfNmN9nc613u4myebbUrVtwBe1cpnHMIhGECjyzEaJ+TajqQfj2YrRTiPpKCcAmb6NFiDY5qBq/YhY2/VsrzY4o3U="
    script: skip # Don't run tests
    deploy:
      provider: script
      script: pub run grinder pkg-github-release pkg-github-linux
      skip_cleanup: true # Don't clean up the Dart SDK.

      # This causes the deploy to only be build when a tag is pushed. This
      # is because the `tag` attribute in `if:` statements has a different
      # understanding of the "current tag" than this, which uses the
      # `TRAVIS_TAG` environment variable. `if:` statements check whether a
      # tag exists that refers to the current commit, whereas `TRAVIS_TAG`
      # checks whether the current build was caused by a tag.
      #
      # We check `if:` because it avoids unnecessary build steps, and
      # `on: {tags: true}` ensures that we only deploy on the build caused
      # by pushing a tag, not the build caused by pushing master.
      on: {tags: true}

  # Deploy to npm.
  - name: npm
    if: *deploy-if
    env:
      # NPM_TOKEN="..."
      - secure: "mf4pySNam2KFYNpYnMSSgQzWHrEUJSbLKhgaSgIq/biEdMO5imeQ/hiK8BvWKw4kzN58C2RCBVafxwWttL86SoBixSMViSxhR29QdVQGm3w6wGUnE7bauCTesFWuYm2Qhz8N7yGs0nWOq4fmLZGnkKhaUm45F3E3/AzAUY/ic5JueyZ74kMa92wx/ENz5aN3tj/TUHx29af3ZYpGTX8lVTaKXpjuu6LPxNU3RWSP0piFSt2sSgXsw7FidbM2JaS5mNCc86SECB/c+YBmvvIiqikZNPyH/kfXxZYRmZn6o2j+k0B3wSaAFWWVnO4dyqia40eIJlwzQ65QUMSZe6mmnLXjeWFwt6qB8s+FuBAUT+4bBSHxNXVGWvcphCrt59jHjssHSuee8CkASn8DWIXql/xAuzHmmqKRVcuA765zJ30dS9polTmPOsvDbcirHomFLypWP3zhePfqkIrwp9alVTMrApluoWtvyYfUgPaffmfKblvJEd3UAiweqUnd7cDG5+d4QubIlNRG+ywHnC9UWBoU9CCL6KuAwJLd0WFIAgKJWS9Yu5h2RBYkLXj0J7htOxdCYO47qsR9u1GFB6Jk8r7TtL9+8t0U0Mo2kX5xvlAPkEZfIzvcst3K467x3b5F4/kYLCxOffRFIn0oEPh9StHmzkWKS84gkqS+CK4/AYI="
    script: skip
    deploy:
      provider: script
      script: pub run grinder pkg-npm-deploy
      skip_cleanup: true
      on: {tags: true}

  # Deploy to pub.
  - name: pub
    if: *deploy-if
    env:
      # PUB_CREDENTIALS="..."
      - secure: "QCNhSiluq2TPf20ekwWlf+TkyzwnGwqS3pU+3XogRlP6ffRcG98zL9pn7cp8xmaM50x9PY6nk0t+oxkiOFw7sKhECfIRv0Z+P4cURhTUJ25+FqLPupCSqehoF93Bx8fXQR+2KCEP+cEeu2dcDU0hAZnzSWliRm/X/6Hfy+2M5eVc4x0+YC/gDjdbNbgH5P29qhRSB7klB8FtKDQdmQro0l1jSe69RGUmaeFSG7ryn+OlCJNMZqwZBd2Yb7pShiegU1ks/fIrC+pf/Yx2/VUscyLGwWqNxl6xXeZko3bNNCNPhPNIjArZJTNKMHvuIvKEvjfrUIr6TwGsw9vJmGjAbSiZzeXfeJ5zBp9ZaL1i8g5WwvVoQcbFgTn/vCisLZ97NP+0ipKr1VXxDfJ+MThaFsbOnl4wcC9XrrqQERWjH4lNGdfywvjql+d1M48veGqeYYY64UhiGDS+98t6GG+Q+ScQh5LDbn/uaQhi6DUCCqzaphdr78ylVrt7RzIdauOcu/CY3q22Kfm+wOZd+4S3Abk3L7P3eWl60sm/yUCx6yTA1rZPBylL5+R3cQS+9Lp9lll03Xcuf/L+MD7pVsN/RB5L52zn51oxtuVvjU01R0JZ8vWSgZ7CMs1BD7DXCjz9deGvBCHJR5aFelygt9ZSuIaM2xpZ2uSFscUnf6qjSh4="
    script: skip
    deploy:
      provider: script
      script: pub run grinder pkg-pub-deploy
      skip_cleanup: true
      on: {tags: true}

  # Deploy to Homebrew.
  - name: Homebrew
    if: *deploy-if
    env: *github-env
    script: skip
    deploy:
      provider: script
      script: pub run grinder pkg-homebrew-update
      skip_cleanup: true
      on: {tags: true}

  - stage: deploy 2
    name: "GitHub: macOS"
    if: *deploy-if
    env: *github-env
    script: skip
    os: osx
    deploy:
      provider: script
      script: pub run grinder pkg-github-macos
      skip_cleanup: true
      on: {tags: true}

  - name: "GitHub: Windows"
    if: *deploy-if
    env: *github-env
    script: skip
    os: windows
    deploy:
      provider: script
      script: pub run grinder pkg-github-windows
      skip_cleanup: true
      on: {tags: true}
