language: dart
branches:
  only:
    - master
    # Semantic version tags and legacy branches of the form "1.2.x".
    - "/^\\d+\\.\\d+\\.(\\d+([+-].*)?|x)$/"
cache:
  directories:
    - $HOME/.pub-cache

before_script:
- if-node() { if [ ! -z "$NODE_VERSION" ]; then "$@"; fi }
- if-dart() { if [ -z "$NODE_VERSION" ]; then "$@"; fi }
- if-node . "$HOME/.nvm/nvm.sh"
- if-node nvm install "$NODE_VERSION"
- if-node nvm use "$NODE_VERSION"
- if-node pub run grinder pkg-npm-dev
- if-dart pub run grinder pkg-standalone-dev

jobs:
  include:
  ## Testing

  # Testing on the Dart VM
  - dart: stable
    dart_task: {test: -x node}
  - dart: dev
    dart_task: {test: -x node}

  # Testing on Node.js
  - env: NODE_VERSION=stable
    dart_task: {test: -t node}
  # Keep these up-to-date with the latest LTS Node releases. They next need to
  # be rotated April 2021. See https://github.com/nodejs/Release.
  - env: NODE_VERSION=lts/dubnium
    dart_task: {test: -t node}
  - env: NODE_VERSION=lts/erbium
    dart_task: {test: -t node}

  # Static checks
  - dart_task: {dartanalyzer: --fatal-warnings --fatal-hints ./}
  # TODO(jathak): Re-enable this once dart-lang/sdk#42989 is fixed.
  # - dart_task: dartfmt

  ## Deployment

  # Sanity check before releasing anywhere.
  - stage: sanity check
    if: &deploy-if
      (type IN (push, api)) AND (repo = sass/migrator) AND tag =~ ^\d+\.\d+\.\d+([+-].*)?$
    script: pub run grinder sanity-check-before-release

  # Deploy Linux releases to GitHub. macOS and Windows releases are deployed in
  # a later stage so that we can build native snapshots on bots with the same
  # operating system.
  - stage: deploy 1
    name: "GitHub: Linux"
    if: *deploy-if
    env: &github-env
      - GITHUB_USER=sassbot
      # GITHUB_TOKEN="..."
      - secure: "tpeP2HUWhw5Ah2LvqU3bFNWgc/XT2qTGnc8RiPMBoMhMOE9QbQwOe9BgeMSuqq7wSPIAznuQ0cyjDWnX/k1fZjRhLeF1DZc0gql4LgHDyc3LL2Y1OIxVIBKsS/od/VRtKUDUnW/0sjVvai06i4HuY/0qRJkQpNJj4Cec7+NDCNGnMprst8NPKz4T8H8ajPRoyeauppSAl/CUlv37zhKKTzL8Q1xEZw5+8lv4arzmix6OgVHHHlVPspHtaKJIWEO3rxzVbq3e6g0S9/tnrosKEOj++WzcxcmhJ200kxo3Q4jMCG3d6OvxVAehaFsOjnH2CXZn6G19pzS2sWPScpx/yMvTkvCGVLg6eHaCDzVRpzvjABo4OwAfAh89H2lkHNG9SMQz3zrBgy4h7+9xxMXD9GT4RkJhnPk5MknrUo8yog1NVP//hakTGmXuUFLUQl0Ls1AJP4m2nPENW5j3uYBWSeyWvRKaqFo0wO6tsgUZYjrttl/dpVInlwQ0LEqwSVpfA0Jns8ReEyRxg4CCf137ELeRBIG81LqsTFHqh+l/j8nnvuLVYU1VAOZyzID56tVqczXbcCcKVIoJHLHnCq2C9irfwVuDVPn2QILvjueab8Y/9NeZZHjltclJidaZ8yD5aGbx93XlpaiovdMrqdB18wsg5TiXT+r/IdM9xB63Npg="
    script: skip # Don't run tests
    deploy:
      provider: script
      script: pub run grinder pkg-github-release pkg-github-linux
      skip_cleanup: true # Don't clean up the Dart SDK.

      # This causes the deploy to only be build when a tag is pushed. This
      # is because the `tag` attribute in `if:` statements has a different
      # understanding of the "current tag" than this, which uses the
      # `TRAVIS_TAG` environment variable. `if:` statements check whether a
      # tag exists that refers to the current commit, whereas `TRAVIS_TAG`
      # checks whether the current build was caused by a tag.
      #
      # We check `if:` because it avoids unnecessary build steps, and
      # `on: {tags: true}` ensures that we only deploy on the build caused
      # by pushing a tag, not the build caused by pushing master.
      on: {tags: true}

  # Deploy to npm.
  - name: npm
    if: *deploy-if
    env:
      # NPM_TOKEN="..."
      - secure: "oQUGdVz/wfwooT+Ix0C5WkeLI25j+vff/NB9OV5uksGg5v62MOugUQZm1w5ldLl2bfM7+9NtX6MPJ31MKmp+nWz33tYJ52cYhdqs80Ogs5OuaBB+IMqZu4EIZMnVkdkpQD4mN09qL9KDIdcVQtmhlu6CZ7iyJR+Ed0MCANhlcOPH9nYkgS+j0NUtkM0IWNSKDo4+MpLR9T5WadJT49vufLiV0p/K5m2UfbqwEJQUjEabamemSVx7AAR5Y2h4tLeOTXbgamtKAizAQvv8dRgFq1gBr5ULQfunxIpZYhzPI8AY0mII3EqJvy/NfKb+mTMEBwrUZs16BrtoWxhFtgOlcvxk86z+e4xKranDYcsbLqlpiPJztknyNgA62SfBDwa0kt7Eg9wKhN/Wy5iYnybo9M7zBu22a7nIpQQnwCz/WWkd7XLdDsMZbzHqcVOzgN5QyUO5YOCRPPUbZGs1OrRHRGGQDtH+C0I35oW86pqwzqnFi62F3EHF4yabaNQDJIqPQMbTzQBYgoijvAWNKlXf/o9p/+Rc+hkyyzg3/egXZzMQ2njfOp1hkauEn4FE4BLE9PHkOrIM7QQaX4gVlZt6DAxh+jOUPyshep6689LgU9uNB4ZOYkdzZy1DKgMSvboYJaT2TqmQnQCL3htRLWhw2SGF3+SEIeZHIHDORgLGz+c="
    script: skip
    deploy:
      provider: script
      script: pub run grinder pkg-npm-deploy
      skip_cleanup: true
      on: {tags: true}

  # Deploy to pub.
  - name: pub
    if: *deploy-if
    env:
      # PUB_CREDENTIALS="..."
      - secure: "QCNhSiluq2TPf20ekwWlf+TkyzwnGwqS3pU+3XogRlP6ffRcG98zL9pn7cp8xmaM50x9PY6nk0t+oxkiOFw7sKhECfIRv0Z+P4cURhTUJ25+FqLPupCSqehoF93Bx8fXQR+2KCEP+cEeu2dcDU0hAZnzSWliRm/X/6Hfy+2M5eVc4x0+YC/gDjdbNbgH5P29qhRSB7klB8FtKDQdmQro0l1jSe69RGUmaeFSG7ryn+OlCJNMZqwZBd2Yb7pShiegU1ks/fIrC+pf/Yx2/VUscyLGwWqNxl6xXeZko3bNNCNPhPNIjArZJTNKMHvuIvKEvjfrUIr6TwGsw9vJmGjAbSiZzeXfeJ5zBp9ZaL1i8g5WwvVoQcbFgTn/vCisLZ97NP+0ipKr1VXxDfJ+MThaFsbOnl4wcC9XrrqQERWjH4lNGdfywvjql+d1M48veGqeYYY64UhiGDS+98t6GG+Q+ScQh5LDbn/uaQhi6DUCCqzaphdr78ylVrt7RzIdauOcu/CY3q22Kfm+wOZd+4S3Abk3L7P3eWl60sm/yUCx6yTA1rZPBylL5+R3cQS+9Lp9lll03Xcuf/L+MD7pVsN/RB5L52zn51oxtuVvjU01R0JZ8vWSgZ7CMs1BD7DXCjz9deGvBCHJR5aFelygt9ZSuIaM2xpZ2uSFscUnf6qjSh4="
    script: skip
    deploy:
      provider: script
      script: pub run grinder pkg-pub-deploy
      skip_cleanup: true
      on: {tags: true}

  # Deploy to Homebrew.
  - name: Homebrew
    if: *deploy-if
    env: *github-env
    script: skip
    deploy:
      provider: script
      script: pub run grinder pkg-homebrew-update
      skip_cleanup: true
      on: {tags: true}

  - stage: deploy 2
    name: "GitHub: macOS"
    if: *deploy-if
    env: *github-env
    script: skip
    os: osx
    deploy:
      provider: script
      script: pub run grinder pkg-github-macos
      skip_cleanup: true
      on: {tags: true}

  - name: "GitHub: Windows"
    if: *deploy-if
    env: *github-env
    script: skip
    os: windows
    deploy:
      provider: script
      script: pub run grinder pkg-github-windows
      skip_cleanup: true
      on: {tags: true}
